#!/bin/bash

# Demo script for focusc - shows how the toolkit works
# Note: This is for documentation purposes. To actually test,
# run ./focusc directly and interact with it.

echo "=== focusc Demo Script ==="
echo ""
echo "This toolkit provides a minimal CLI for focus sessions and time tracking."
echo ""
echo "To build:"
echo "  gcc -Wall -Wextra -O2 main.c -o focusc"
echo ""
echo "To run:"
echo "  ./focusc"
echo ""
echo "--- Example Interactive Session ---"
echo ""
echo "$ ./focusc"
echo "=== Focus & Time-Tracking Toolkit ==="
echo "Controls: Enter=stop timer, k=pause/resume"
echo ""
echo "Enter task name: Write CLI tool"
echo "Task: Write CLI tool"
echo "Timer: 00:00:00"
echo "Timer: 00:00:01"
echo "Timer: 00:00:02"
echo "Timer: 00:00:03"
echo "[User presses k to pause]"
echo "Timer: 00:00:03"
echo "[Paused - timer stays at 00:00:03]"
echo "[User presses k again to resume]"
echo "Timer: 00:00:04"
echo "Timer: 00:00:05"
echo "[User presses Enter to stop]"
echo ""
echo "Task: Write CLI tool"
echo "Time spent: 00:00:05"
echo ""
echo "Menu:"
echo "1. Start next task"
echo "2. End session"
echo "Choice (1-2): 1"
echo ""
echo "Enter task name: Test and debug"
echo "Task: Test and debug"
echo "Timer: 00:00:00"
echo "Timer: 00:00:01"
echo "Timer: 00:00:02"
echo "[User presses Enter to stop]"
echo ""
echo "Task: Test and debug"
echo "Time spent: 00:00:02"
echo ""
echo "Menu:"
echo "1. Start next task"
echo "2. End session"
echo "Choice (1-2): 2"
echo ""
echo "=== Session Summary ==="
echo ""
echo "Task Name                            Time      Bar"
echo "---                                  ---       "
echo "Write CLI tool                       00:00:05  ####################"
echo "Test and debug                       00:00:02  ########"
echo ""
echo "=== Statistics ==="
echo "Total session time: 00:00:07"
echo "Average task duration: 00:00:03"
echo "Tasks completed: 2"
echo ""
echo "Session ended."
echo ""
echo "--- Features ---"
echo "✓ Live timer updates every second"
echo "✓ Pause/resume with 'k' key"
echo "✓ Session summary with ASCII bar chart"
echo "✓ No external dependencies"
echo "✓ Pure POSIX terminal I/O"
echo "✓ All data in memory"
